chenglou/react-motion

App0.js, App1.js, App2.js
I didn’t listen to your README warning.
This looks awesome.
=> Add standard CSS `transform` property

Demo1.js, Demo2.js, index.html
Wanted to see how this performed on mobile browsers. Only tested in an iOS simulator so far, but it nailed it.
=> Touch support

demo1/Demo.jsx
Quick "semi-hacky" way to enable Demo#1 for mobile devices
=> - Enabling touchMove support for mobile devices for Demo #1

Spring.jsx, stepper.js
@chenglou Since I saw your talk at React Europe(I was there) and I wanted to use Spring asap, this pull request is aimed to remove the hack, because I basically don't want my user slow down animations on fat keydowns :D
=> Remove hack

Spring.jsx
Unused vars, dead code, redefined vars
=> Syntax fixes

README.md, bower.json
Added a bower.json file so more people can enjoy this awesome library. Didn't register the package, it's super easy though http://bower.io/docs/creating-packages/#register.
=> added bower.json

Spring.jsx, stepper.js, utils.js
=> Syntax: use const

stepper.js
More accurate and much more stable. <https://en.wikipedia.org/wiki/Semi-implicit_Euler_method>
=> Use semi-implicit Euler integration.

package.json, server.js, webpack.config.js
=> Add ESLint loader for compile-time checks

.gitignore
Fixes especially annoying npm-debug.log
=> Update gitignore from Github .gitignore template

.eslintrc, Spring.js, demo0/Demo.jsx, demo1/Demo.jsx, demo2/Demo.jsx, demo3/Demo.jsx, demo4/Demo.jsx, package.json, utils.js
One-by one syntax/lint fixes...
=> Lint fixes / Demo0

demo1/Demo.jsx
A bit nitty gritty, but it confused me when trying react-motion for the first time. I tried to do a similar thing as in this demo, but I used === instead (which doesn't eval as true for undefined and null, but == does).
=> Current positions is undefined at first render

server.js
You know, so we can easily test on other devices.
=> Expose dev server to the network.

src/filter.js, test/filter-test.js
=> Iterate over items added during filtering.

src/Spring.js
tests pass, demos work, doesn't break regular web webpack builds.
I just want my name in this repo
=> react-native 'compatibility'

package.json
See http://semver.npmjs.com/
I think it might also work for rc, but I am not sure.
=> Fix React 0.14 compatibility for all beta

test/Spring-test.js
Here's a list of the added tests:
- parent kill child Spring
- TS unmount/mount correctly (and https://github.com/chenglou/react-motion/issues/77)
- init value + final value
- TS init value + final value
=> Add more tests.

src/components.js
TransitionSpring should likely have the same fix for unmounting that Spring element has regarding state mutation.
=> Fix unmounted state mutation

README.md
Hi,
First of all thanks for this great library.
as the first time using this library, the README did not help me to know how to get the Spring out of the library, it is not mentioned anywhere in the README and I think it is important as a "Getting Started".
The examples didn't help neither because they directly requires the Spring file (I think it should be better to extract the things from the library root).
So for now, maybe I'm wrong, but the only way to figure this out is to look at the library code.
Thanks
=> improve the doc to indicate how to get Spring

demos/demo3/Demo.jsx
In response to this issue https://github.com/chenglou/react-motion/issues/137
=> updated todos to show mounting animation

src/animationLoop.js
Tbh just want my name in this repo
=> Fix typo in animationLoop.js

.eslintignore, test/Spring-test.js, test/createMockRaf.js
fixes these lint errors, fixes #144 
```
demos/demo6/babel.js
0:0  error  Maximum call stack size exceeded
native/index.js
1:0   error  Strict mode is not permitted                                     strict
7:0   error  Unexpected var, use let or const instead                         no-var
7:0   error  All "var" declarations must be at the top of the function scope  vars-on-top
9:0   error  All "var" declarations must be at the top of the function scope  vars-on-top
9:0   error  Unexpected var, use let or const instead                         no-var
11:0   error  All "var" declarations must be at the top of the function scope  vars-on-top
11:0   error  Unexpected var, use let or const instead                         no-var
13:0   error  All "var" declarations must be at the top of the …
```
=> eslint fixes

.eslintignore
=> lint fix : demo - demos

test/stripStyle-test.js
While fixing #180, I noticed that stripStyle() was untested, so I
decided to add a couple of basic tests here.
=> Add some tests for stripStyle()

karma.conf.js, package.json, server.js, webpack.config.js, webpack.prod.config.js
Some minor changes to npm scripts and configs so they all fully run under Windows.
=> Windows-compatible npm-scripts, fixes #191

webpack.config.js
=> Update webpack config to support new Demo folders, fixes #197

server.js
=> Development env should be set before webpack config is loaded

package.json
I added react to devDependencies so when you make clean install on dev you don't have to install react separately.
Tested all demos, no issues with react@0.14
=> Support React@0.14

README.md
=> Fix link to spring param chooser on readme

README.md
out of discussions here: https://github.com/chenglou/react-motion/issues/229
=> spring() documentation update

.npmignore, README.md, bower.json
=> Use NPMCDN bower.zip package, fixes #250

demos/demo4-photo-gallery/Demo.jsx
While trying demos, thought i was missing these buttons. So, let me know if it's a good idea to have it with the demos?
=> Added buttons for carousel!

AUTHORS, LICENSE
#282, but against the right branch (`development`)
=> Add AUTHORS

README.md
- updated the value property name to style.
- added information about the style property
- fixes #288
=> Update the doc about willLeave

.flowconfig, src/Motion.js, src/StaggeredMotion.js, src/TransitionMotion.js, src/Types.js
Fixed the curl brace spacing as requested in https://github.com/chenglou/react-motion/pull/295
=> Flow update

src/Motion.js, src/StaggeredMotion.js, src/TransitionMotion.js
[ref](https://github.com/jquery/jquery/issues/3143)
=> Use RAF timestamp argument if available

.eslintrc, demos/demo8-draggable-list/Demo.jsx
Changed variable names to more descriptive ones.
=> Draggable list demo variable names

bower.json, package.json, test/Motion-test.js, test/StaggeredMotion-test.js, test/TransitionMotion-test.js
=> Use 'react-dom/test-utils' package instead of 'react-addons-test-utils'

package.json, src/Motion.js, src/StaggeredMotion.js, src/TransitionMotion.js, src/Types.js
this PR updates the flow version, and adds new annotations based on https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627
=> update flow, fix component annotations

src/Motion.js, src/StaggeredMotion.js, src/TransitionMotion.js, src/Types.js
Reverts chenglou/react-motion#485
onlyChild returns a ReactElement
=> Revert "Upgrade typings to flow 0.53.1"

.babelrc, .flowconfig, .size-snapshot.json, package.json, rollup.config.js, yarn.lock
- enable loose mode for env and class properties
- reuse helpers from babel runtime instead of duplicating them
This change saved us 2kb minified.
=> Improve babel config
