Spring.jsx

When a dto has null values, the recursive calls on the payload cause the calculation to explode on a null check.

adding null check for endValue because sometimes payloads have nulls

---

server.js
webpack.config.js

Default is 3000, but can be overriden
```bash
16:23 $ npm start
> react-motion@0.0.1 start /Users/nkbt/nkbt/react-animation
> NODE_ENV=development node server.js
Listening at localhost:3000
```
```bash
16:23 $ PORT=3001 npm start
> react-motion@0.0.1 start /Users/nkbt/nkbt/react-animation
> NODE_ENV=development node server.js
Listening at localhost:3001
```

Configurable dev port

---

.eslintignore
package.json

So we can safely process all files (future proof). And it is simply more convenient way to run `eslint .`

Add .eslintignore

---

src/Spring.js
src/mapTree.js
src/reorderKeys.js

This is more for stylistic and purity reasons, but here is a completely-unscientific performance explanation:
To handle `let`/`const` block scoping, Babel (loose mode) compiles this:
```js
function interpolateValue(alpha, nextValue, prevValue) {
/* ... */
if (nextValue.val != null) {
let ret = {
val: interpolateValue(alpha, nextValue.val, prevValue.val),
};
/* ... */
return ret;
}
/* ... */
if (isPlainObject(nextValue)) {
const ret = {};
Object.keys(nextValue).forEach(key => {
ret[key] = interpolateValue(alpha, nextValue[key], prevValue[key]);
});
return ret;
}
return nextValue;
}
```
to this:
```js
"use strict";
function interpolateValue(alpha, nextValue, prevValue) {
/* ... */
if (nextValue.val != null) {
var ret = {
val: interpolateValue(alpha, nextValue.val, prevValue.val)
};
/* ... …
```

Replace `forEach` with `reduce` for object creation

---

src/Spring.js
src/mapTree.js
src/noVelocity.js

Hi there!
When using react-motion in case-sensitive environments (Linux/Ubuntu), we run into an issue where node, webpack and possibly others can't properly require in the `lodash.isplainobject` module due to current spelling. Note, we've worked around this issue for now by simply aliasing inside of webpack but ideally I think we should use the true name of the module.

corrects imports of lodash.isplainobject module

---

demos/demo3/Demo.jsx
src/Spring.js
src/compareTrees.js

This makes `willLeave` simpler and have a better default behavior. The way to
tell the `TransitionSpring` before this was to add an if statement at the top of
`willLeave` to check if `currValue` has reached the destination and that the
`currVelocity` is 0 and then returning null if yes. We now do that check
internally and do the unmounting when `currValue` is equal to the return of
`endValue` and `currVelocity` is 0.
This "fixes" #104 by just deprecating the API.

Make `willLeave` stop when `currVelocity` is 0 and `currValue` reached dest

---

demos/demo0/Demo.jsx
src/updateTree.js
test/Spring-test.js

This will allow something like:
```js
<Spring defaultValue={0} endValue={100}>
{val => <div >{val}</div>}
</Spring>
```
We're overloading `endValue` and stepping away from the consistency we had before with `val` and `config`. But this use case seems common enough, and explicit enough, that react-motion could handle it. There is very little confusion as to whether the `Spring` will or not interpolate the _only_ thing it's given.

Passing scalars to `endValue`

---

test/Spring-test.js
test/createMockRaf.js

The title says it all.
I also adapted the tests to use that mock `raf`. The main advantages of using a mock `raf` is that the tests become synchronous, making them much easier to reason about. They also make the whole system deterministic. This means that when we call `mockRaf.step()` 10 times with the same Spring (and same constants),  `currValue` will always take the same values in the same order.
There are two main functions that can be used:
- `mockRaf.step(ms = 16)` - will step "time" by one frame and by `ms` amount of milliseconds. This will call all `raf`s that were registered in the last frame.
- `mockRaf.manySteps(numberOfSteps = 1)` - will call `mockRaf.step` `numberOfSteps` times
The two other functions are the mock functions. They can be used like follow:
```js
const injector …
```

Add mockRaf (combining mocks for `raf` and `performance-now`)

---

src/animationLoop.js
test/Spring-test.js

Seems like this bug was introduced [here](https://github.com/chenglou/react-motion/commit/ff5399b2cb9ba8127d6b6b4cce5d8a5c8a3f90eb).
We calculate the `frameNumber` next frames, but never update
`prevNextState` which is the state passed to `step`. So we just
calculate the same frame over and over again.
Added test to prevent this next time.

Fix animationLoop when iterating over more than 1 frame.

---

src/components.js
test/Spring-test.js

We [mutate](https://github.com/chenglou/react-motion/blob/84985fd8bc0f10d4477bbfbf5bf779dfa3be85f9/src/components.js#L48-L50) `currValue[key]` when a new element enters the scene. This could be
reflected in user land. If you push `currValue` in an array inside the
child-as-function in the `TransitionSpring`, then you'd see that element get
mutated when a new element entered the scene.

Remove mutation inside `TransitionSpring` when new key enters

---

src/animationLoop.js
test/Spring-test.js

This one was hard to track down. Say you have two springs one inside
the other, there's the `owner` and the `child`. They both mount, and
therefore call `startAnimation` which will register a `raf`.
The `child` steps first because it registered the `raf` callback first.
In the step it checks `noVelocity` and say in our case it's true, it'll
calls `stopAnimation`. `stopAnimation` will set `val.active = false`.
Then the `owner` steps.
We then loop through the `Spring`s, starting with the `child` and
render them. We render the `child` and check if `child.active` is true.
In our case it's not, so we don't push it in the array of future `raf`s.
We then render the `owner` which makes the `child` render and call
`startAnimation`. The call to `startAnimation` will set
`val.active = true`, but …

Fix a bug in animationLoop when having nested Springs.

---

package.json

Hey there :)
I’m the author of inject-loader. This PR gets react-motion off the master branch of inject-loader and onto a published version (2.0.1 to be precise), which now includes the code that necessitated using master in the past

Update inject-loader to use 2.0.1 now it’s published

---

package.json

A know issue with [browserify-cdn](https://www.google.co.in/search?q=browserify+cdn+peerdependencies&oq=browserify+cdn+pee&aqs=chrome.0.69i59j69i57j69i60.5598j1j7&sourceid=chrome&es_sm=91&ie=UTF-8), is that it fails on peerDependencies. As such, it tries to bundle react, doesn't find it installed, and [bails with an error](https://wzrd.in/standalone/react-motion). This should fix that.

ignore react for browserify build

---

package.json

To enable smooth usage of React 0.14 RC1 without NPM errors on install.

Update React peerDependency to rc1

---

src/components.js

I was working on a component that uses react-motion and noticed that it caused react to throw the setState warning when I went to a new route. I located the source of this issue in `src/components.js` in TransitionSpring's `animationRender` method. The Spring component sets `this.hasUnmounted` to `false` in `componentWillUnmount` but TransitionSpring does not. When `animationRender` checks `!this.hasUnmounted` it evaluates to true and the setState code is run causing react to throw the warning. So I added `this.hasUnmounted = true;` to `componentWillUnmount` in TransitionSpring. The warning is no longer thrown.

set this.hasUnmounted to false in componentWillUnmount method of the TransitionSpring component

---

README.md

It was missing the change directory step.
It was trying to run `npm i` && `npm run dev` on parent directory.

Fix the build it yourself one-liner

---

package.json

Hi, when I tried to run `npm test`, it failed at first because the `jasmine-core` dependency was missing. Per karma-jasmine documentation (https://github.com/karma-runner/karma-jasmine) since 0.3.0 you need to add an explicit `jasmine-core` dependency since karma-jasmine does not pull it any more.

Add missing jasmine dependency.

---

src/hasReachedStyle.js
src/noVelocity.js
src/stripStyle.js
src/updateTree.js
test/hasReachedStyle-test.js
test/noVelocity-test.js
test/stripStyle-test.js
test/updateTree-test.js

I am upgrading from 0.2.7 to 0.3.0 and I ran into an error:
> Uncaught TypeError: Cannot read property 'config' of undefined
This happens when I am using a `TransitionMotion` with a style object
that has a key who's value is `undefined`, e.g.:
{
opacity: spring(0),
extraText: undefined,
}
To make react-motion easier to work with, I have added guards in a
number of places.
Fixes #180.

Handle `undefined` and `null` in style objects

---

.travis.yml
README.md
package.json

This will tell Travis CI how to test this project. This configuration
needs to be coupled with someone who has permissions on the GitHub repo
to enable the Travis CI webhook.
The nyan cat reporter didn't work very well in the Travis output, so I
decided to just use the default reporter for this integration.
[Closes #182]

Add Travis CI configuration

---

package.json

Works ok for me. If in doubts, you can always run commands one-by-one manually...
```sh
git fetch origin
git checkout gh-pages
git reset --hard origin/gh-pages 
git rebase origin/master --force-rebase
npm run build-demos
git add .
git commit --amend --no-edit
git push origin gh-pages --force
git checkout master
```
```sh
C:\www\react-animation (auto-gh-pages)
λ npm run gh-pages
> react-motion@0.3.0 gh-pages C:\www\react-animation
> git fetch origin && git checkout gh-pages && git reset --hard origin/gh-pages && git rebase origin/master --force-rebase && npm run build-demos && git add . && git commit --amend --no-edit && git push origin gh-pages --force && git checkout master
Switched to branch 'gh-pages'
Your branch is up-to-date with 'origin/gh-pages'.
HEAD is now at 5de8fa2 Build …
```

Automate publish to gh-pages

---

.npmignore

Noticed that latest NPM package release (0.3.0) contains Sublime configuration files, which seems like got there accidentally. To prevent it further, it's better to ignore those files from adding to NPM package.

Ignore sublime configuration files

---

src/stepper.js

Looks like it's better to check x with rest value, not previous.
For example if errorMargin becomes a user parameter, there will situations with small velocity and small dx values but x is far from the rest.

Switch to compare x with rest on errorMargin check

---

package.json

If you try to build currently from a fresh clone, you get:
```
rm: lib/*: No such file or directory
```
This fixes that by tracking an empty `lib` in git.

Add /lib/.gitignore to fix build error

---

src/Motion.js
test/Motion-test.js

I don't intend for this to land until after I've used it and made sure we're solving the right problem, but I'm opening this now so @chenglou can play with it (and maybe add Flow if there are places I've missed).
See also #235.

Add Motion.@onRest

---

src/TransitionMotion.js

This fixes the TransitionMotion component not unmounting nicely. I am not 100% this is the right way to do this or why I am having so much trouble reproducing this using react-motion only.

Try fixing souporserious/react-motion-ui-pack#41 by checking if unmounting is in progress.

---

src/TransitionMotion.js

Since 0.4.4 flowtype complains
```
node_modules/react-motion/src/TransitionMotion.js:508
508:     this.unmounting = true;
^^^^^^^^^^ property `unmounting`. Property not found in
186: const TransitionMotion = React.createClass({
^ React component
```

Fix flow for TransitionMotion.unmounting

---

src/Motion.js
src/StaggeredMotion.js
src/TransitionMotion.js
src/Types.js

In later versions of flow, it requires that generic types have their
type parameters specified. All of the `ReactElement` declarations were
throwing an error saying these needed to be specified.
This change updates `ReactElement` to `React$Element<*>`

Fix Flow ReactElement errors

---

src/Motion.js
src/StaggeredMotion.js
src/TransitionMotion.js
src/Types.js

I think git/github somehow got confused when both #361 and #371 were merged in rebase mode. Some changes in #371 were overwritten by #361. This pull request fixes that.

Fix merge errors

---

.eslintrc
demos/demo8-draggable-list/Demo.jsx

Issue - Originally on every mouse move event the reinsert function was called to reorder list item positions. 
Fix - Added an if clause to ensure that "order" state items are only reordered when positional changes actually occur in the DOM.

Performance optimisation for draggable list demo

---

README.md
src/TransitionMotion.js
src/Types.js
test/TransitionMotion-test.js
test/index.js

Had a case where the index of each element was essential for correct visual representation. `didLeave` can be used to keep track of what elements `<TransitionMotion />` is still animating.
Can also be used as the `onRest` equivalent for `<TransitionMotion />`.

Add didLeave method to <TransitionMotion />

---

.flowconfig
demos/demo2-draggable-balls/Demo.jsx

Made demo variable names more descriptive

Refactored demo and fixed flow check errors

---

src/TransitionMotion.js

This code in `TransitionMotion` was a source of bug for us in testing. 
```js
if (this.unmounting) {
return;
}
// TODO: when config is {a: 10} and dest is {a: 10} do we raf once and
// call cb? No, otherwise accidental parent rerender causes cb trigger
this.animationID = defaultRaf((timestamp) => {
const propStyles = this.props.styles;
...
this.setState({
currentStyles: newCurrentStyles,
currentVelocities: newCurrentVelocities,
lastIdealStyles: newLastIdealStyles,
lastIdealVelocities: newLastIdealVelocities,
mergedPropsStyles: newMergedPropsStyles,
});
...
}
```
The problem is that if execution passes the conditional `if (this.unmounting)`, then executes async `defaultRaf` and after that component unmounts and after that the callback of `defaultRaf` is called, then `setState` will be …

Unmounted component setState fix

---

README.md

Typings are now nested under the "/types" directory. Fixes #442

Fix link to TypeScript types

---

README.md
demos/demo0-simple-transition/Demo.jsx
demos/demo1-chat-heads/Demo.jsx
demos/demo2-draggable-balls/Demo.jsx
demos/demo3-todomvc-list-transition/Demo.jsx
demos/demo4-photo-gallery/Demo.jsx
demos/demo5-spring-parameters-chooser/Demo.jsx
demos/demo7-water-ripples/Demo.jsx
demos/demo8-draggable-list/Demo.jsx
package.json
src/Motion.js
src/StaggeredMotion.js
src/TransitionMotion.js
test/Motion-test.js
test/StaggeredMotion-test.js
test/TransitionMotion-test.js

Fixes #445
I think we should migrate to the es6 `class` syntax and stop using `React.createClass`, but that would be another step. For now just created this PR, so people stop having deprecation warnings after migration to React v15.5. 
If you feel the same about `class`, I'll create an issue about it, so the matter won't get forgotten and neglected.

Migrated deprecated React.PropTypes and React.createClass

---

bower.json
test/Motion-test.js
test/StaggeredMotion-test.js
test/TransitionMotion-test.js

Update deprecated 'create-react-class' dependencies in tests to ES6 classes

---

.travis.yml

Would get better logs in Travis. And Node 4 is a bit dated...

Split tests in Travis and use Node 6

---

src/Motion.js
src/StaggeredMotion.js
src/TransitionMotion.js
src/Types.js

I simply ran the `flow-upgrade` command, and fixed the `ReactElement` types. I didn't change anything else, perhaps you'd like me to replace the `import  * as React` (which is what flow-upgrade does) by more granular imports?

Upgrade typings to flow 0.53.1

---

src/Motion.js
src/StaggeredMotion.js
src/TransitionMotion.js

This diff achieves two things:
1. applies solution from #420 to `Motion` and `StaggeredMotion`
2. prevents two `rAF`s to be triggered at the same time
In some rare cases **ReactFiber** can execute `cWRP` right after `setState` call, which would result in two `rAF`s to be triggered (2nd point addresses this) and this combined with `setState` being triggered after unmounting the component (#420 addressed that, but only for `TransitionMotion`), the `rAF` would never stop, as it would work on stale state, which can result in OOM for low-memory and long-running devices.

Fixed memory leak

---

package.json

Update performance-now to ^2.1.0
> react-motion has a dependency of performance-now@^0.2.0
> 
> It also has a dependency on raf@^3.1.0 which currently resolves to raf@3.4.0
> 
> raf@3.40 has a dependency on performance-now@^2.1.0
> 
> This means that including react-motion as a dependency introduces 2 major versions of raf.
chenglou/react-motion#507

chenglou/react-motion#507 performance-now update
